spring:
  application:
    name: eureka-consumer-loadbalancer

server:
  port: 9000
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/

