spring:
  application:
    name: config-client
  cloud:
    bus:
      trace:
        enabled: true
      enabled: true
server:
  port: 1300
management:
  endpoints:
    web:
      exposure:
        include: refresh