spring:
  application:
    name: eureka-server
server:
  port: 7000
eureka:
  instance:
    hostname: localhost
  client:
    # 表示是否将自己注册到 Eureka Server，默认为 true。
    register-with-eureka: false
    # 表示是否从 Eureka Server 获取注册信息，默认为 true。
    fetch-registry: false
    # 设置与 Eureka Server 交互的地址，查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
