spring:
  application:
    name: eureka-server
server:
  port: 7001
eureka:
  instance:
    hostname: peer1
  client:
    # 表示是否将自己注册到 Eureka Server，默认为 true。
    register-with-eureka: true
    # 表示是否从 Eureka Server 获取注册信息，默认为 true。
    fetch-registry: true
    # 设置与 Eureka Server 交互的地址，查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://peer2:7002/eureka/
