server:
  port: 1200
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zzmmcc/spring-cloud-study-demo.git
          search-paths: config-repo