spring:
  application:
    name: trace-b
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
    base-url: http://120.79.193.209:9411/  # 指定了 Zipkin 服务器的地址
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
server:
  port: 2101